In [1]:
import numpy as np

# ----------------------------
# Arrays
# ----------------------------
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

print("Array 1:", arr1)
print("Array 2:", arr2)

print("\n=== Array Operations ===")
print("Addition:", arr1 + arr2)
print("Subtraction:", arr1 - arr2)
print("Multiplication:", arr1 * arr2)
print("Division:", arr1 / arr2)

# ----------------------------
# Matrices
# ----------------------------
mat1 = np.array([[1, 2],
                 [3, 4]])

mat2 = np.array([[5, 6],
                 [7, 8]])

print("\nMatrix 1:\n", mat1)
print("\nMatrix 2:\n", mat2)

print("\n=== Matrix Operations ===")
print("Addition:\n", mat1 + mat2)
print("Subtraction:\n", mat1 - mat2)
print("Element-wise Multiplication:\n", mat1 * mat2)
print("Element-wise Division:\n", mat1 / mat2)

# Matrix multiplication
print("\nMatrix Multiplication:\n", np.matmul(mat1, mat2))

# Alternative matrix multiplication using @ operator
print("\nMatrix Multiplication (@):\n", mat1 @ mat2)

Array 1: [10 20 30 40]
Array 2: [1 2 3 4]

=== Array Operations ===
Addition: [11 22 33 44]
Subtraction: [ 9 18 27 36]
Multiplication: [ 10  40  90 160]
Division: [10. 10. 10. 10.]

Matrix 1:
 [[1 2]
 [3 4]]

Matrix 2:
 [[5 6]
 [7 8]]

=== Matrix Operations ===
Addition:
 [[ 6  8]
 [10 12]]
Subtraction:
 [[-4 -4]
 [-4 -4]]
Element-wise Multiplication:
 [[ 5 12]
 [21 32]]
Element-wise Division:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]

Matrix Multiplication:
 [[19 22]
 [43 50]]

Matrix Multiplication (@):
 [[19 22]
 [43 50]]


In [2]:
import os
print(os.getcwd())

C:\Users\akash
